### PR TITLE
fix: repair iOS docs and cargo doc CI builds

### LINKED ISSUE #3428: iOS docs build broken on main
See the two failed GitHub Actions. Put together a fix

https://github.com/xmtp/libxmtp/actions/runs/24223412849
https://github.com/xmtp/libxmtp/actions/runs/24223412857

### PR DESCRIPTION
**Pull request by xmtp-coder-agent**
Resolves https://github.com/xmtp/libxmtp/issues/3428

## Summary

Fixes both broken docs CI workflows on main:

### Deploy Docs (cargo doc) — `deploy-docs.yml`
- **Root cause:** `log_parser` depends on `slint` → `fontique` v0.7.0, which fails to compile on Ubuntu due to `fontconfig_sys` API mismatch
- **Fix:** Exclude `log_parser` from `dev/docs` (`--exclude log_parser`). It's a GUI tool, not an API library — no reason to include it in workspace docs

### iOS Docs (jazzy) — `docs-ios.yml`
- **Root cause 1:** `xcode-version: "16.0"` doesn't support `swift-tools-version: 6.1` (introduced in d49d8557). Swift 6.1 requires Xcode 16.3+
- **Root cause 2:** Jazzy runs from `sdks/ios/` (`working-directory`) but `Package.swift` is at the repo root. `sourcekitten` invokes `swift build` from the wrong directory
- **Fix:** Update Xcode to 16.3 and pass `--source-directory ${{ github.workspace }}` so jazzy finds `Package.swift` at the repo root

## Test plan
- [ ] `deploy-docs.yml` workflow passes (cargo doc succeeds without fontique compilation error)
- [ ] `docs-ios.yml` workflow passes (jazzy finds Package.swift and builds with Xcode 16.3)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

> [!NOTE]
> ### Fix iOS docs and cargo doc CI builds
> - Updates the iOS docs workflow to use Xcode 16.3, run the bindings script directly (without a Nix dev shell), and write Jazzy output to an absolute workspace path with `--source-directory` specified.
> - Excludes the `log_parser` crate from `cargo doc` generation in [dev/docs](https://github.com/xmtp/libxmtp/pull/3430/files#diff-99f6b915660b496bb9ff7305e7bb589ce2fd1ce07624095a20d3d690703ae0f8) to fix the cargo doc CI build.
>
> 
>
> <sup><a href="https://app.macroscope.com">Macroscope</a> summarized 99f5ecc.</sup>
> 
>

### CODE REVIEW

File: .github/workflows/docs-ios.yml [hunk 1]
```diff
@@ -29,7 +29,7 @@ jobs:
           cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
       - uses: maxim-lobanov/setup-xcode@v1
         with:
-          xcode-version: "16.0"
+          xcode-version: "16.3"
       - name: Build bindings
         run: nix develop .#ios --command ./sdks/ios/dev/bindings
```
Comment (neekolas) [inline .github/workflows/docs-ios.yml]: We don't need to run this command via `nix` anymore. You can just run the script directly.

**Comment by xmtp-coder-agent** [comment]
Addressed @neekolas's feedback: removed the `nix develop .#ios --command` wrapper from the Build bindings step. The script is now invoked directly since it handles nix internally.

**Review by neekolas — APPROVED** [review]
